### ISSUE TITLE
The fancy Unicode-chars breaks my terminal

### ISSUE THREAD

**Issue by JohnPhoto** [bstream/dots#13]
Could you please make the fancy pansy Unicode-chars optional or atleast possible to opt-out?

They break my terminal since they print 2 squares instead of 1 char and therefore pushes the timestamp to the next line and breaks everything.

**Comment by bstream** [comment]
This can be solved by locally overwriting the default behaviour. The fancy unicode symbols are set in `fish/config.fish`. 

Example:
* In `fish/config.fish`: Include a line loading your overwrites like this: `. path/to/custom.fish.config`.
* In `path/to/custom.fish.config` overwrite the unicode chars like so:
```
...
set -g __fish_git_prompt_char_stagedstate '>'
```
