### ISSUE TITLE
.gitconfig breaks everything

### ISSUE THREAD

**Issue by JohnPhoto** [bstream/dots#3]
Still issues with trying to update please make a section in readme.md of how to migrate old versions of dots. Even if it is `rm -rf ./`

```
update                               (master *+|MERGING<>) 08:28:02
Updating dots
rc/gitconfig: unmerged (f2365f2bbf347c012e61060b3adeb950ff9837dd)
rc/gitconfig: unmerged (c72906aaafa17bb0ad5e88e1b56a7a8c9ff46cdf)
rc/gitconfig: unmerged (ef7ae1e5d81874845de9ecdf5fdfbb024849ef99)
fatal: git-write-tree: error building trees
Cannot save the current index state
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
No stash found.
````

**Comment by bstream** [comment]
Can you add a snapshot of your dots directory and the git status of that directory?
Do you know which version you have (had when you ran update?)
The current commit hash can be found with `git rev-parse HEAD`

**Comment by bstream** [comment]
I think that this solved (I added a troubleshooting section to the readme file that explains how to reset the dots installation if merge conflicts happen), please get back to me otherwise.

**Comment by JohnPhoto** [comment]
Worked nicely with a hard reset and reinstall.
